name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  show-env-context:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v2

      - name: Environment context
        run: |
          node -v
          npm -v
          yarn -v

  slackNotification:
    name: Slack Notification Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Slack Notification Demo
        uses: bryannice/gitactions-slack-notification@2.0.0
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
          SLACK_MESSAGE: "Demo'ing the Slack Notification"
          SLACK_TITLE: 'Slack Notification Demo'
